# These are supported funding model platforms

github: ["hctilg", "ReeraAI"] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#buy_me_a_coffee: "hctilg_void" # Replace with a single Buy Me a Coffee username
custom: ["https://daramet.com/hctilg"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
